"use client";
import { CheckCircle2, Clipboard, KeyRound, Store, XCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { Button, Spinner, useToast } from "@/components/ui";
import { useAppState } from "@/hooks/use-app-state";
import type { Settings } from "@/lib/types";

function SettingsForm({ settings, refresh }: { settings: Settings; refresh: () => Promise<void> }) {
  const toast = useToast();
  const [form, setForm] = useState({ storeName: settings.storeName, phone: settings.phone, welcomeMessage: settings.welcomeMessage, demoMode: settings.demoMode, businessTimezone: settings.businessTimezone, businessHours: settings.businessHours, awayMessage: settings.awayMessage, outsideHoursBot: settings.outsideHoursBot });
  const [health, setHealth] = useState<{ configured: boolean; connected: boolean } | null>(null);
  const [jobs, setJobs] = useState<Array<{ id: number; job_type: string; status: string; attempt_count: number; last_error_code: string | null }>>([]);
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/line/health").then(async (response) => setHealth(await response.json() as { configured: boolean; connected: boolean })).catch(() => setHealth({ configured: settings.hasAccessToken, connected: false })); fetch("/api/jobs").then(async(response)=>{const body=await response.json() as {items:Array<{ id:number;job_type:string;status:string;attempt_count:number;last_error_code:string|null}>};setJobs(body.items);}).catch(()=>setJobs([])); }, [settings.hasAccessToken]);
  async function save(e: React.FormEvent) {
    e.preventDefault(); setBusy(true); setError("");
    const response = await fetch("/api/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) });
    setBusy(false);
    if (response.ok) { toast("บันทึกการตั้งค่าแล้ว"); await refresh(); } else setError("บันทึกไม่สำเร็จ กรุณาตรวจสอบข้อมูล");
  }
  async function copy() { await navigator.clipboard.writeText(settings.webhookUrl); toast("คัดลอก Webhook URL แล้ว"); }
  const workdays = [["1", "จ."], ["2", "อ."], ["3", "พ."], ["4", "พฤ."], ["5", "ศ."]] as const;
  return <form noValidate onSubmit={save} className="mt-6 space-y-6">
    <section className="panel p-5 sm:p-6"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-slate-100"><Store size={19}/></div><div><h2 className="text-lg font-semibold">ข้อมูลร้าน</h2><p className="text-sm text-slate-500">ข้อมูลที่ใช้ในข้อความตอบกลับ</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block font-medium">ชื่อร้าน</span><input className="control w-full px-3" value={form.storeName} onChange={(e)=>setForm({...form,storeName:e.target.value})}/></label><label><span className="mb-2 block font-medium">เบอร์ติดต่อ</span><input className="control w-full px-3" value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})}/></label><label className="sm:col-span-2"><span className="mb-2 block font-medium">ข้อความต้อนรับ</span><textarea rows={4} className="control w-full px-3 py-3" value={form.welcomeMessage} onChange={(e)=>setForm({...form,welcomeMessage:e.target.value})}/></label></div></section>
    <section className="panel p-5 sm:p-6"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-slate-100"><KeyRound size={19}/></div><div><h2 className="text-lg font-semibold">LINE OA</h2><p className="text-sm text-slate-500">Credentials อ่านจาก Server Environment เท่านั้น</p></div><span className={`ml-auto flex items-center gap-1 text-sm font-medium ${health?.connected ? "text-emerald-700" : "text-red-700"}`}>{health?.connected ? <><CheckCircle2 size={17}/>เชื่อมต่อแล้ว</> : <><XCircle size={17}/>{health?.configured ? "ตรวจสอบไม่ผ่าน" : "ยังตั้งค่าไม่ครบ"}</>}</span></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-[160px_1fr]"><dt className="text-slate-500">Channel ID</dt><dd><code>{settings.channelId ? `${settings.channelId.slice(0,4)}••••${settings.channelId.slice(-4)}` : "ยังไม่ตั้งค่า"}</code></dd><dt className="text-slate-500">Secret / Token</dt><dd>จัดการใน Vercel Environment Variables เท่านั้น</dd></dl><div className="mt-5 border-t border-slate-200 pt-5"><div className="font-medium">Webhook URL</div><div className="mt-2 flex gap-2"><code className="min-w-0 flex-1 overflow-x-auto rounded-lg bg-slate-100 px-3 py-3 text-xs">{settings.webhookUrl}</code><Button type="button" variant="outline" onClick={()=>void copy()}><Clipboard size={17}/>คัดลอก</Button></div></div></section>
    <section className="panel p-5 sm:p-6"><h2 className="text-lg font-semibold">เวลาทำการ</h2><p className="mt-1 text-sm text-slate-500">Timezone: Asia/Bangkok</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{workdays.map(([day,label])=>{const value=form.businessHours[day] ?? ["09:00","18:00"]; return <div key={day} className="grid grid-cols-[44px_1fr_1fr] items-center gap-2"><span>{label}</span><input type="time" className="control px-2" value={value[0]} onChange={(e)=>setForm({...form,businessHours:{...form.businessHours,[day]:[e.target.value,value[1]]}})}/><input type="time" className="control px-2" value={value[1]} onChange={(e)=>setForm({...form,businessHours:{...form.businessHours,[day]:[value[0],e.target.value]}})}/></div>})}</div><label className="mt-4 block"><span className="mb-2 block font-medium">ข้อความนอกเวลาทำการ</span><textarea rows={3} className="control w-full px-3 py-3" value={form.awayMessage} onChange={(e)=>setForm({...form,awayMessage:e.target.value})}/></label><label className="mt-4 flex min-h-11 items-center gap-3"><input type="checkbox" checked={form.outsideHoursBot} onChange={(e)=>setForm({...form,outsideHoursBot:e.target.checked})}/>ให้ Automation ตอบ FAQ นอกเวลาทำการ</label></section>
    <section className="panel p-5"><div className="flex items-center justify-between gap-4"><div><h2 className="font-semibold">Demo Mode</h2><p className="text-sm text-slate-500">U_DEMO จะไม่เรียก LINE API</p></div><button type="button" role="switch" aria-checked={form.demoMode} onClick={()=>setForm({...form,demoMode:!form.demoMode})} className={`relative h-7 w-12 rounded-full ${form.demoMode?"bg-[#06c755]":"bg-slate-300"}`}><span className={`absolute left-1 top-1 size-5 rounded-full bg-white shadow ${form.demoMode?"translate-x-5":""}`}/></button></div></section>
    <section className="panel p-5"><h2 className="font-semibold">งาน Retry / Dead-letter</h2>{jobs.length===0?<p className="mt-2 text-sm text-slate-500">ไม่มีงานที่ต้องตรวจสอบ</p>:<div className="mt-3 divide-y divide-slate-100">{jobs.slice(0,10).map((job)=><div key={job.id} className="flex min-h-11 items-center justify-between gap-3 py-2 text-sm"><span>{job.job_type} #{job.id}</span><span className={job.status==="DEAD"?"text-red-700":"text-amber-700"}>{job.status} · ครั้งที่ {job.attempt_count} · {job.last_error_code??"UNKNOWN"}</span></div>)}</div>}</section>
    <div className="flex items-center justify-between"><div role="alert" className="text-sm text-red-600">{error}</div><Button type="submit" busy={busy}>บันทึกการตั้งค่า</Button></div>
  </form>;
}

export default function SettingsPage() { const { data, loading, refresh }=useAppState(); if(loading||!data)return <Spinner/>; return <div className="mx-auto max-w-[900px]"><h1 className="page-title">การตั้งค่า</h1><p className="mt-2 text-slate-500">ข้อมูลร้าน การเชื่อมต่อ และเวลาทำการ</p><SettingsForm settings={data.settings} refresh={refresh}/></div>; }
