"use client";
import{createContext,useCallback,useContext,useEffect,useState,type ReactNode}from"react";import{AlertTriangle,Check,LoaderCircle,X}from"lucide-react";import clsx from"clsx";
type Tone="success"|"error"|"info";const ToastContext=createContext<(message:string,tone?:Tone)=>void>(()=>{});
export function ToastProvider({children}:{children:ReactNode}){const[toasts,setToasts]=useState<Array<{id:number;message:string;tone:Tone}>>([]);const notify=useCallback((message:string,tone:Tone="success")=>{const id=Date.now();setToasts(items=>[...items.filter(item=>item.message!==message),{id,message,tone}]);setTimeout(()=>setToasts(items=>items.filter(item=>item.id!==id)),3500)},[]);return <ToastContext.Provider value={notify}>{children}<div className="fixed bottom-20 right-4 z-[80] flex max-w-sm flex-col gap-2 md:bottom-5" aria-live="polite">{toasts.map(toast=><div key={toast.id} className={clsx("flex items-center gap-3 rounded-xl border bg-white px-4 py-3 shadow-lg",toast.tone==="error"?"border-red-200":"border-slate-200")}>{toast.tone==="error"?<AlertTriangle size={18} className="text-red-600"/>:<Check size={18} className="text-emerald-600"/>}<span>{toast.message}</span></div>)}</div></ToastContext.Provider>}
export const useToast=()=>useContext(ToastContext);
export function Button({children,variant="primary",busy=false,className,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"outline"|"ghost"|"danger";busy?:boolean}){return <button {...props} disabled={busy||props.disabled} className={clsx("inline-flex min-h-11 items-center justify-center gap-2 rounded-[10px] px-4 py-2 text-sm font-semibold transition-colors",variant==="primary"&&"bg-[#06c755] text-white hover:bg-[#05a847]",variant==="outline"&&"border border-slate-300 bg-white hover:bg-slate-50",variant==="ghost"&&"hover:bg-slate-100",variant==="danger"&&"bg-red-600 text-white hover:bg-red-700",className)}>{busy?<LoaderCircle size={17} className="animate-spin"/>:children}</button>}
export function EmptyState({title,body,action}:{title:string;body:string;action?:ReactNode}){return <div className="flex min-h-52 flex-col items-center justify-center p-8 text-center"><div className="mb-4 grid size-11 place-items-center rounded-full bg-slate-100"><span className="block size-2 rounded-full bg-slate-400"/></div><h3 className="font-semibold">{title}</h3><p className="mt-1 max-w-sm text-sm text-slate-500">{body}</p>{action&&<div className="mt-4">{action}</div>}</div>}
export function Spinner({label="กำลังโหลดข้อมูล"}:{label?:string}){return <div className="flex min-h-56 items-center justify-center gap-3 text-slate-500"><LoaderCircle className="animate-spin" size={20}/><span>{label}</span></div>}
export function Status({value}:{value:string}){return <span className={`status status-${value.toLowerCase()}`}>{value}</span>}
export function Dialog({open,title,description,confirmLabel="ยืนยัน",danger=false,onClose,onConfirm,busy=false}:{open:boolean;title:string;description:string;confirmLabel?:string;danger?:boolean;onClose:()=>void;onConfirm:()=>void;busy?:boolean}){useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose()};document.addEventListener("keydown",handler);return()=>document.removeEventListener("keydown",handler)},[open,onClose]);if(!open)return null;return <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/35 p-4" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div role="alertdialog" aria-modal="true" aria-labelledby="dialog-title" aria-describedby="dialog-description" className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><h2 id="dialog-title" className="text-lg font-semibold">{title}</h2><p id="dialog-description" className="mt-2 text-sm leading-6 text-slate-600">{description}</p></div><button aria-label="ปิด" onClick={onClose} className="grid size-11 place-items-center rounded-lg hover:bg-slate-100"><X size={18}/></button></div><div className="mt-6 flex justify-end gap-3"><Button autoFocus variant="outline" onClick={onClose}>ยกเลิก</Button><Button variant={danger?"danger":"primary"} busy={busy} onClick={onConfirm}>{confirmLabel}</Button></div></div></div>}
