"use client";
import Image from "next/image";
import { ArrowLeft, Check, CircleAlert, Clock3, Info, RotateCcw, Search, Send, UserRoundCheck, X, XCircle } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Button, EmptyState, Spinner, Status, useToast } from "@/components/ui";
import type { Conversation, Message } from "@/lib/types";

const time = (value: string) => new Intl.DateTimeFormat("th-TH", { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Bangkok" }).format(new Date(value));
const iso = (value: unknown) => new Date(String(value)).toISOString();
const mapMessage = (row: Record<string, unknown>): Message => ({
  id: Number(row.id), conversationId: Number(row.conversation_id), sender: row.sender as Message["sender"], body: String(row.body), createdAt: iso(row.created_at),
  messageType: String(row.message_type ?? "text"), deliveryStatus: String(row.delivery_status ?? "RECEIVED") as Message["deliveryStatus"], payload: (row.payload ?? {}) as Record<string, unknown>,
  mediaUrl: row.media_url ? String(row.media_url) : null, mimeType: row.mime_type ? String(row.mime_type) : null, fileName: row.file_name ? String(row.file_name) : null,
  fileSize: row.file_size ? Number(row.file_size) : null, lastErrorCode: row.last_error_code ? String(row.last_error_code) : null, internal: Boolean(row.internal),
});
function Avatar({ conversation, size = "size-10" }: { conversation: Conversation; size?: string }) { const customer=conversation.customer; return customer.pictureUrl ? <span role="img" aria-label={customer.displayName} className={`${size} shrink-0 rounded-full bg-cover bg-center`} style={{backgroundImage:`url(${customer.pictureUrl})`}}/> : <span className={`grid ${size} shrink-0 place-items-center rounded-full bg-slate-100 font-semibold`}>{customer.displayName.slice(0,1)}</span>; }

export default function InboxPage() {
  const params=useSearchParams(); const toast=useToast();
  const [conversations,setConversations]=useState<Conversation[]>([]); const [messages,setMessages]=useState<Message[]>([]); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(""); const [page,setPage]=useState(1); const [hasMore,setHasMore]=useState(false);
  const [selectedId,setSelectedId]=useState<number|undefined>(params.get("conversation")?Number(params.get("conversation")):undefined); const [pane,setPane]=useState<"list"|"chat"|"detail">("list");
  const [message,setMessage]=useState(""); const [pendingKey,setPendingKey]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  const selected=useMemo(()=>conversations.find((item)=>item.id===(selectedId??conversations[0]?.id)),[conversations,selectedId]);

  async function loadConversations(nextPage=1, append=false) { const response=await fetch(`/api/conversations?page=${nextPage}&limit=30&q=${encodeURIComponent(query)}`,{cache:"no-store"}); if(!response.ok)throw new Error(); const body=await response.json() as {items:Conversation[];hasMore:boolean}; setConversations((old)=>append?[...old,...body.items]:body.items); setHasMore(body.hasMore); setPage(nextPage); if(!selectedId&&body.items[0])setSelectedId(body.items[0].id); }
  async function loadMessages(id:number) { const response=await fetch(`/api/conversations/${id}/messages?limit=50`,{cache:"no-store"}); if(!response.ok)throw new Error(); const body=await response.json() as {items:Record<string,unknown>[]}; setMessages(body.items.map(mapMessage)); }
  useEffect(()=>{const timer=setTimeout(()=>{setLoading(true); loadConversations().catch(()=>toast("โหลดรายการไม่สำเร็จ","error")).finally(()=>setLoading(false));},300); return()=>clearTimeout(timer);},[query]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(!selected)return; let active=true; let delay=3000; let timer:ReturnType<typeof setTimeout>; const poll=async()=>{try{await loadMessages(selected.id);delay=3000;}catch{delay=Math.min(delay*2,15000);} if(active)timer=setTimeout(poll,delay);}; void poll(); return()=>{active=false;clearTimeout(timer);};},[selected?.id]); // eslint-disable-line react-hooks/exhaustive-deps
  function select(id:number){setSelectedId(id);setPane("chat");}
  async function action(name:"takeover"|"resume"|"close") { if(!selected)return; setBusy(true); const response=await fetch(`/api/conversations/${selected.id}/${name}`,{method:"POST"}); setBusy(false); if(response.ok){toast(name==="takeover"?"รับช่วงการสนทนาแล้ว":name==="resume"?"ส่งกลับให้ Automation แล้ว":"ปิดการสนทนาแล้ว");await loadConversations(page);}else toast("เปลี่ยนสถานะไม่สำเร็จ","error"); }
  async function send(e:React.FormEvent){e.preventDefault();if(!selected||!message.trim())return;const key=pendingKey??crypto.randomUUID();setPendingKey(key);setBusy(true);const response=await fetch(`/api/conversations/${selected.id}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,idempotencyKey:key})});setBusy(false);if(response.ok){setMessage("");setPendingKey(null);await Promise.all([loadMessages(selected.id),loadConversations(page)]);}else toast("ส่งข้อความไม่สำเร็จ","error");}
  async function retry(id:number){setBusy(true);const response=await fetch(`/api/messages/${id}/retry`,{method:"POST"});setBusy(false);if(response.ok&&selected)await loadMessages(selected.id);else toast("Retry ไม่สำเร็จ","error");}
  if(loading&&conversations.length===0)return <Spinner/>;
  return <div className="mx-auto max-w-[1460px]"><div className="mb-5"><h1 className="page-title">กล่องข้อความ</h1><p className="mt-2 text-slate-500">ส่งข้อความจริง ติดตามสถานะ และควบคุม Automation</p></div><section className="panel min-h-[calc(100dvh-190px)] overflow-hidden"><div className="grid min-h-[inherit] lg:grid-cols-[320px_minmax(380px,1fr)_320px]">
    <aside className={`${pane!=="list"?"hidden":"flex"} min-h-[inherit] flex-col border-r border-slate-200 lg:flex`}><div className="border-b border-slate-200 p-3"><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input className="control w-full pl-10 pr-11" placeholder="ค้นหาการสนทนา" value={query} onChange={(e)=>setQuery(e.target.value)}/>{query&&<button aria-label="ล้างการค้นหา" onClick={()=>setQuery("")} className="absolute right-0 top-0 grid size-11 place-items-center"><X size={16}/></button>}</div></div><div className="flex-1 divide-y divide-slate-100 overflow-auto">{conversations.length===0?<EmptyState title="ไม่พบการสนทนา" body="ลองใช้คำค้นหาอื่น"/>:conversations.map((item)=><button key={item.id} onClick={()=>select(item.id)} className={`flex w-full gap-3 p-4 text-left hover:bg-slate-50 ${selected?.id===item.id?"bg-emerald-50":""}`}><Avatar conversation={item}/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><span className="font-semibold">{item.customer.displayName}</span><time className="text-xs text-slate-400">{time(item.lastMessageAt)}</time></div><div className="mt-1 truncate text-sm text-slate-500">{item.lastMessage}</div><div className="mt-2"><Status value={item.status}/></div></div></button>)}</div>{hasMore&&<Button variant="outline" className="m-3" onClick={()=>void loadConversations(page+1,true)}>โหลดเพิ่มเติม</Button>}</aside>
    <main className={`${pane!=="chat"?"hidden":"flex"} min-h-[inherit] flex-col lg:flex`}>{selected?<><header className="flex min-h-16 items-center gap-3 border-b border-slate-200 px-3 sm:px-5"><button aria-label="กลับไปรายการ" onClick={()=>setPane("list")} className="grid size-11 place-items-center lg:hidden"><ArrowLeft size={19}/></button><Avatar conversation={selected}/><div className="min-w-0 flex-1"><div className="font-semibold">{selected.customer.displayName}</div><Status value={selected.status}/></div><button aria-label="ดูข้อมูลลูกค้า" onClick={()=>setPane("detail")} className="grid size-11 place-items-center lg:hidden"><Info size={19}/></button></header>
      <div className="flex-1 space-y-4 overflow-auto bg-slate-50/60 p-4 sm:p-6">{messages.map((item)=>item.internal?<div key={item.id} className="text-center text-xs text-slate-500">{item.body} · {time(item.createdAt)}</div>:<div key={item.id} className={`flex ${item.sender==="CUSTOMER"?"justify-start":"justify-end"}`}><div className={`max-w-[82%] rounded-2xl px-4 py-3 ${item.sender==="CUSTOMER"?"border border-slate-200 bg-white":item.sender==="SYSTEM"?"bg-slate-200":"bg-emerald-100"}`}><div className="mb-1 text-[11px] font-semibold text-slate-500">{item.sender==="CUSTOMER"?"ลูกค้า":item.sender==="SYSTEM"?"ระบบ":"Admin"}</div>{item.messageType==="image"&&item.mediaUrl?<Image src={item.mediaUrl} alt="รูปจากลูกค้า" width={320} height={240} unoptimized className="mb-2 max-h-64 rounded-lg object-contain"/>:item.mediaUrl?<a className="mb-2 block font-medium text-blue-700 underline" href={item.mediaUrl}>{item.fileName??`เปิด${item.messageType}`}</a>:null}<p className="whitespace-pre-wrap leading-6">{item.body}</p><div className="mt-1 flex items-center justify-end gap-1 text-[10px] text-slate-500"><time>{time(item.createdAt)}</time>{item.deliveryStatus==="SENDING"||item.deliveryStatus==="QUEUED"?<><Clock3 size={12}/>กำลังส่ง</>:item.deliveryStatus==="SENT"?<><Check size={12}/>ส่งแล้ว</>:item.deliveryStatus==="FAILED"?<><CircleAlert size={12}/>ส่งไม่สำเร็จ <button className="ml-1 min-h-8 underline" disabled={busy} onClick={()=>void retry(item.id)}><RotateCcw size={12} className="inline"/> Retry</button></>:null}</div></div></div>)}</div>
      <div className="border-t border-slate-200 bg-white p-3"><div className="mb-3 flex flex-wrap gap-2">{selected.status!=="ADMIN"&&selected.status!=="CLOSED"&&<Button onClick={()=>void action("takeover")} busy={busy}><UserRoundCheck size={18}/>รับช่วง</Button>}{(selected.status==="ADMIN"||selected.status==="WAITING")&&<Button variant="outline" onClick={()=>void action("resume")} busy={busy}><RotateCcw size={18}/>ส่งกลับ Automation</Button>}{selected.status!=="CLOSED"&&<Button variant="outline" onClick={()=>void action("close")} busy={busy}><XCircle size={18}/>ปิดงาน</Button>}</div><form onSubmit={send} className="flex gap-2"><input className="control min-w-0 flex-1 px-3" placeholder={selected.status==="ADMIN"?"พิมพ์ข้อความถึงลูกค้า...":"รับช่วงก่อนส่งข้อความ"} value={message} onChange={(e)=>setMessage(e.target.value)} disabled={selected.status!=="ADMIN"}/><Button type="submit" busy={busy} disabled={selected.status!=="ADMIN"||!message.trim()}><Send size={18}/><span className="hidden sm:inline">ส่ง</span></Button></form></div></>:<EmptyState title="ยังไม่มีการสนทนา" body="ข้อความจากลูกค้าจะปรากฏที่นี่"/>}</main>
    <aside className={`${pane!=="detail"?"hidden":"block"} border-l border-slate-200 p-5 lg:block`}>{selected?<><div className="flex items-center gap-3"><button aria-label="กลับไปแชต" onClick={()=>setPane("chat")} className="grid size-11 place-items-center lg:hidden"><ArrowLeft size={19}/></button><h2 className="text-lg font-semibold">ข้อมูลลูกค้า</h2></div><div className="mt-5 flex items-center gap-3"><Avatar conversation={selected} size="size-12"/><div><div className="font-semibold">{selected.customer.displayName}</div><div className="text-xs text-slate-500">{selected.customer.lineUserId}</div></div></div><dl className="mt-6 grid grid-cols-[110px_1fr] gap-y-3 text-sm"><dt className="text-slate-500">เบอร์โทร</dt><dd>{selected.customer.phone||"ยังไม่มี"}</dd><dt className="text-slate-500">Profile</dt><dd>{selected.customer.profileSyncedAt?"ซิงก์แล้ว":"รอซิงก์"}</dd><dt className="text-slate-500">สินค้า</dt><dd>{selected.customer.interestedProduct||"ยังไม่ระบุ"}</dd></dl><div className="mt-6 flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs text-slate-500"><Clock3 size={16}/>อัปเดตล่าสุด {time(selected.lastMessageAt)}</div></>:<EmptyState title="เลือกการสนทนา" body="ข้อมูลลูกค้าจะปรากฏที่นี่"/>}</aside>
  </div></section></div>;
}
